#!/bin/bash
# -----------------------------------------------------------------------------
# docker-teamspeak /start script
# -----------------------------------------------------------------------------

# Run the teamspeak server
export LD_LIBRARY_PATH=/opt/teamspeak
cd /opt/teamspeak
./ts3server_linux_amd64 logpath=/data/logs/ dbsqlpath=/data/
